resolver: lts-7.19

packages:
- '.'

extra-deps:
  - katip-0.3.1.4

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
